Add warning for not being in the right conda environment

diff --git a/scripts/opss25-planviz b/scripts/opss25-planviz
--- a/scripts/opss25-planviz
+++ b/scripts/opss25-planviz
@@ -2,5 +2,11 @@
 set -e  # exit on error
 
 DIR="$HOME/opss25/packages/PlanViz/external/PlanViz"
+ENV_NAME="opss25"
+
+if [[ "$CONDA_DEFAULT_ENV" != "$ENV_NAME" ]]; then
+        echo "❌ You must be in the $ENV_NAME conda environment. Please activate it first by running 'conda deactivate $ENV_NAME'. Aborting."
+        exit 1
+fi
 
 python "$DIR/script/run.py" "$@"
